/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateTopicRequestDataReplicasAssignmentsInner struct for CreateTopicRequestDataReplicasAssignmentsInner
type CreateTopicRequestDataReplicasAssignmentsInner struct {
	PartitionId *int32 `json:"partition_id,omitempty"`
	BrokerIds []int32 `json:"broker_ids,omitempty"`
}

// NewCreateTopicRequestDataReplicasAssignmentsInner instantiates a new CreateTopicRequestDataReplicasAssignmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTopicRequestDataReplicasAssignmentsInner() *CreateTopicRequestDataReplicasAssignmentsInner {
	this := CreateTopicRequestDataReplicasAssignmentsInner{}
	return &this
}

// NewCreateTopicRequestDataReplicasAssignmentsInnerWithDefaults instantiates a new CreateTopicRequestDataReplicasAssignmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTopicRequestDataReplicasAssignmentsInnerWithDefaults() *CreateTopicRequestDataReplicasAssignmentsInner {
	this := CreateTopicRequestDataReplicasAssignmentsInner{}
	return &this
}

// GetPartitionId returns the PartitionId field value if set, zero value otherwise.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) GetPartitionId() int32 {
	if o == nil || isNil(o.PartitionId) {
		var ret int32
		return ret
	}
	return *o.PartitionId
}

// GetPartitionIdOk returns a tuple with the PartitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) GetPartitionIdOk() (*int32, bool) {
	if o == nil || isNil(o.PartitionId) {
    return nil, false
	}
	return o.PartitionId, true
}

// HasPartitionId returns a boolean if a field has been set.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) HasPartitionId() bool {
	if o != nil && !isNil(o.PartitionId) {
		return true
	}

	return false
}

// SetPartitionId gets a reference to the given int32 and assigns it to the PartitionId field.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) SetPartitionId(v int32) {
	o.PartitionId = &v
}

// GetBrokerIds returns the BrokerIds field value if set, zero value otherwise.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) GetBrokerIds() []int32 {
	if o == nil || isNil(o.BrokerIds) {
		var ret []int32
		return ret
	}
	return o.BrokerIds
}

// GetBrokerIdsOk returns a tuple with the BrokerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) GetBrokerIdsOk() ([]int32, bool) {
	if o == nil || isNil(o.BrokerIds) {
    return nil, false
	}
	return o.BrokerIds, true
}

// HasBrokerIds returns a boolean if a field has been set.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) HasBrokerIds() bool {
	if o != nil && !isNil(o.BrokerIds) {
		return true
	}

	return false
}

// SetBrokerIds gets a reference to the given []int32 and assigns it to the BrokerIds field.
func (o *CreateTopicRequestDataReplicasAssignmentsInner) SetBrokerIds(v []int32) {
	o.BrokerIds = v
}

func (o CreateTopicRequestDataReplicasAssignmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PartitionId) {
		toSerialize["partition_id"] = o.PartitionId
	}
	if !isNil(o.BrokerIds) {
		toSerialize["broker_ids"] = o.BrokerIds
	}
	return json.Marshal(toSerialize)
}

type NullableCreateTopicRequestDataReplicasAssignmentsInner struct {
	value *CreateTopicRequestDataReplicasAssignmentsInner
	isSet bool
}

func (v NullableCreateTopicRequestDataReplicasAssignmentsInner) Get() *CreateTopicRequestDataReplicasAssignmentsInner {
	return v.value
}

func (v *NullableCreateTopicRequestDataReplicasAssignmentsInner) Set(val *CreateTopicRequestDataReplicasAssignmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTopicRequestDataReplicasAssignmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTopicRequestDataReplicasAssignmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTopicRequestDataReplicasAssignmentsInner(val *CreateTopicRequestDataReplicasAssignmentsInner) *NullableCreateTopicRequestDataReplicasAssignmentsInner {
	return &NullableCreateTopicRequestDataReplicasAssignmentsInner{value: val, isSet: true}
}

func (v NullableCreateTopicRequestDataReplicasAssignmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTopicRequestDataReplicasAssignmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


