/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SubjectAccessReview struct for SubjectAccessReview
type SubjectAccessReview struct {
	Namespace *string `json:"namespace,omitempty"`
	Action *string `json:"action,omitempty"`
	Resource *string `json:"resource,omitempty"`
}

// NewSubjectAccessReview instantiates a new SubjectAccessReview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubjectAccessReview() *SubjectAccessReview {
	this := SubjectAccessReview{}
	return &this
}

// NewSubjectAccessReviewWithDefaults instantiates a new SubjectAccessReview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubjectAccessReviewWithDefaults() *SubjectAccessReview {
	this := SubjectAccessReview{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetNamespace() string {
	if o == nil || isNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetNamespaceOk() (*string, bool) {
	if o == nil || isNil(o.Namespace) {
    return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasNamespace() bool {
	if o != nil && !isNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *SubjectAccessReview) SetNamespace(v string) {
	o.Namespace = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetAction() string {
	if o == nil || isNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetActionOk() (*string, bool) {
	if o == nil || isNil(o.Action) {
    return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasAction() bool {
	if o != nil && !isNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *SubjectAccessReview) SetAction(v string) {
	o.Action = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetResource() string {
	if o == nil || isNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetResourceOk() (*string, bool) {
	if o == nil || isNil(o.Resource) {
    return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasResource() bool {
	if o != nil && !isNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *SubjectAccessReview) SetResource(v string) {
	o.Resource = &v
}

func (o SubjectAccessReview) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !isNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !isNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	return json.Marshal(toSerialize)
}

type NullableSubjectAccessReview struct {
	value *SubjectAccessReview
	isSet bool
}

func (v NullableSubjectAccessReview) Get() *SubjectAccessReview {
	return v.value
}

func (v *NullableSubjectAccessReview) Set(val *SubjectAccessReview) {
	v.value = val
	v.isSet = true
}

func (v NullableSubjectAccessReview) IsSet() bool {
	return v.isSet
}

func (v *NullableSubjectAccessReview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubjectAccessReview(val *SubjectAccessReview) *NullableSubjectAccessReview {
	return &NullableSubjectAccessReview{value: val, isSet: true}
}

func (v NullableSubjectAccessReview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubjectAccessReview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


