/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KafkaRbacSummaryList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KafkaRbacSummaryList{}

// KafkaRbacSummaryList struct for KafkaRbacSummaryList
type KafkaRbacSummaryList struct {
	Kind *string `json:"kind,omitempty"`
	ApiVersion *string `json:"apiVersion,omitempty"`
	Items []KafkaRbacSummary `json:"items,omitempty"`
}

// NewKafkaRbacSummaryList instantiates a new KafkaRbacSummaryList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaRbacSummaryList() *KafkaRbacSummaryList {
	this := KafkaRbacSummaryList{}
	return &this
}

// NewKafkaRbacSummaryListWithDefaults instantiates a new KafkaRbacSummaryList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaRbacSummaryListWithDefaults() *KafkaRbacSummaryList {
	this := KafkaRbacSummaryList{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *KafkaRbacSummaryList) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaRbacSummaryList) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *KafkaRbacSummaryList) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *KafkaRbacSummaryList) SetKind(v string) {
	o.Kind = &v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *KafkaRbacSummaryList) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaRbacSummaryList) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *KafkaRbacSummaryList) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *KafkaRbacSummaryList) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *KafkaRbacSummaryList) GetItems() []KafkaRbacSummary {
	if o == nil || IsNil(o.Items) {
		var ret []KafkaRbacSummary
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaRbacSummaryList) GetItemsOk() ([]KafkaRbacSummary, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KafkaRbacSummaryList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KafkaRbacSummary and assigns it to the Items field.
func (o *KafkaRbacSummaryList) SetItems(v []KafkaRbacSummary) {
	o.Items = v
}

func (o KafkaRbacSummaryList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KafkaRbacSummaryList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableKafkaRbacSummaryList struct {
	value *KafkaRbacSummaryList
	isSet bool
}

func (v NullableKafkaRbacSummaryList) Get() *KafkaRbacSummaryList {
	return v.value
}

func (v *NullableKafkaRbacSummaryList) Set(val *KafkaRbacSummaryList) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaRbacSummaryList) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaRbacSummaryList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaRbacSummaryList(val *KafkaRbacSummaryList) *NullableKafkaRbacSummaryList {
	return &NullableKafkaRbacSummaryList{value: val, isSet: true}
}

func (v NullableKafkaRbacSummaryList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaRbacSummaryList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


