/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KafkaApplicationList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KafkaApplicationList{}

// KafkaApplicationList struct for KafkaApplicationList
type KafkaApplicationList struct {
	Kind *string `json:"kind,omitempty"`
	ApiVersion *string `json:"apiVersion,omitempty"`
	Items []KafkaApplication `json:"items,omitempty"`
}

// NewKafkaApplicationList instantiates a new KafkaApplicationList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaApplicationList() *KafkaApplicationList {
	this := KafkaApplicationList{}
	return &this
}

// NewKafkaApplicationListWithDefaults instantiates a new KafkaApplicationList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaApplicationListWithDefaults() *KafkaApplicationList {
	this := KafkaApplicationList{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *KafkaApplicationList) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaApplicationList) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *KafkaApplicationList) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *KafkaApplicationList) SetKind(v string) {
	o.Kind = &v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *KafkaApplicationList) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaApplicationList) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *KafkaApplicationList) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *KafkaApplicationList) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *KafkaApplicationList) GetItems() []KafkaApplication {
	if o == nil || IsNil(o.Items) {
		var ret []KafkaApplication
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaApplicationList) GetItemsOk() ([]KafkaApplication, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KafkaApplicationList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KafkaApplication and assigns it to the Items field.
func (o *KafkaApplicationList) SetItems(v []KafkaApplication) {
	o.Items = v
}

func (o KafkaApplicationList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KafkaApplicationList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableKafkaApplicationList struct {
	value *KafkaApplicationList
	isSet bool
}

func (v NullableKafkaApplicationList) Get() *KafkaApplicationList {
	return v.value
}

func (v *NullableKafkaApplicationList) Set(val *KafkaApplicationList) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaApplicationList) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaApplicationList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaApplicationList(val *KafkaApplicationList) *NullableKafkaApplicationList {
	return &NullableKafkaApplicationList{value: val, isSet: true}
}

func (v NullableKafkaApplicationList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaApplicationList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


