/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GenericListKafkaRbacSummary struct for GenericListKafkaRbacSummary
type GenericListKafkaRbacSummary struct {
	Kind *string `json:"kind,omitempty"`
	Items []KafkaRbacSummary `json:"items,omitempty"`
}

// NewGenericListKafkaRbacSummary instantiates a new GenericListKafkaRbacSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericListKafkaRbacSummary() *GenericListKafkaRbacSummary {
	this := GenericListKafkaRbacSummary{}
	return &this
}

// NewGenericListKafkaRbacSummaryWithDefaults instantiates a new GenericListKafkaRbacSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericListKafkaRbacSummaryWithDefaults() *GenericListKafkaRbacSummary {
	this := GenericListKafkaRbacSummary{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *GenericListKafkaRbacSummary) GetKind() string {
	if o == nil || isNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericListKafkaRbacSummary) GetKindOk() (*string, bool) {
	if o == nil || isNil(o.Kind) {
    return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *GenericListKafkaRbacSummary) HasKind() bool {
	if o != nil && !isNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *GenericListKafkaRbacSummary) SetKind(v string) {
	o.Kind = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GenericListKafkaRbacSummary) GetItems() []KafkaRbacSummary {
	if o == nil || isNil(o.Items) {
		var ret []KafkaRbacSummary
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericListKafkaRbacSummary) GetItemsOk() ([]KafkaRbacSummary, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GenericListKafkaRbacSummary) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KafkaRbacSummary and assigns it to the Items field.
func (o *GenericListKafkaRbacSummary) SetItems(v []KafkaRbacSummary) {
	o.Items = v
}

func (o GenericListKafkaRbacSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableGenericListKafkaRbacSummary struct {
	value *GenericListKafkaRbacSummary
	isSet bool
}

func (v NullableGenericListKafkaRbacSummary) Get() *GenericListKafkaRbacSummary {
	return v.value
}

func (v *NullableGenericListKafkaRbacSummary) Set(val *GenericListKafkaRbacSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericListKafkaRbacSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericListKafkaRbacSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericListKafkaRbacSummary(val *GenericListKafkaRbacSummary) *NullableGenericListKafkaRbacSummary {
	return &NullableGenericListKafkaRbacSummary{value: val, isSet: true}
}

func (v NullableGenericListKafkaRbacSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericListKafkaRbacSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


