/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubjectAccessReview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubjectAccessReview{}

// SubjectAccessReview struct for SubjectAccessReview
type SubjectAccessReview struct {
	Kind *string `json:"kind,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Verb string `json:"verb"`
	Resource string `json:"resource"`
	ResourceName *string `json:"resourceName,omitempty"`
	User *string `json:"user,omitempty"`
	ResourceAPIGroup *string `json:"resourceAPIGroup,omitempty"`
	ResourceAPIVersion *string `json:"resourceAPIVersion,omitempty"`
}

// NewSubjectAccessReview instantiates a new SubjectAccessReview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubjectAccessReview(verb string, resource string) *SubjectAccessReview {
	this := SubjectAccessReview{}
	this.Verb = verb
	this.Resource = resource
	return &this
}

// NewSubjectAccessReviewWithDefaults instantiates a new SubjectAccessReview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubjectAccessReviewWithDefaults() *SubjectAccessReview {
	this := SubjectAccessReview{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *SubjectAccessReview) SetKind(v string) {
	o.Kind = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *SubjectAccessReview) SetNamespace(v string) {
	o.Namespace = &v
}

// GetVerb returns the Verb field value
func (o *SubjectAccessReview) GetVerb() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Verb
}

// GetVerbOk returns a tuple with the Verb field value
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetVerbOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verb, true
}

// SetVerb sets field value
func (o *SubjectAccessReview) SetVerb(v string) {
	o.Verb = v
}

// GetResource returns the Resource field value
func (o *SubjectAccessReview) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *SubjectAccessReview) SetResource(v string) {
	o.Resource = v
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetResourceName() string {
	if o == nil || IsNil(o.ResourceName) {
		var ret string
		return ret
	}
	return *o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetResourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceName) {
		return nil, false
	}
	return o.ResourceName, true
}

// HasResourceName returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasResourceName() bool {
	if o != nil && !IsNil(o.ResourceName) {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given string and assigns it to the ResourceName field.
func (o *SubjectAccessReview) SetResourceName(v string) {
	o.ResourceName = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *SubjectAccessReview) SetUser(v string) {
	o.User = &v
}

// GetResourceAPIGroup returns the ResourceAPIGroup field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetResourceAPIGroup() string {
	if o == nil || IsNil(o.ResourceAPIGroup) {
		var ret string
		return ret
	}
	return *o.ResourceAPIGroup
}

// GetResourceAPIGroupOk returns a tuple with the ResourceAPIGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetResourceAPIGroupOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceAPIGroup) {
		return nil, false
	}
	return o.ResourceAPIGroup, true
}

// HasResourceAPIGroup returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasResourceAPIGroup() bool {
	if o != nil && !IsNil(o.ResourceAPIGroup) {
		return true
	}

	return false
}

// SetResourceAPIGroup gets a reference to the given string and assigns it to the ResourceAPIGroup field.
func (o *SubjectAccessReview) SetResourceAPIGroup(v string) {
	o.ResourceAPIGroup = &v
}

// GetResourceAPIVersion returns the ResourceAPIVersion field value if set, zero value otherwise.
func (o *SubjectAccessReview) GetResourceAPIVersion() string {
	if o == nil || IsNil(o.ResourceAPIVersion) {
		var ret string
		return ret
	}
	return *o.ResourceAPIVersion
}

// GetResourceAPIVersionOk returns a tuple with the ResourceAPIVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubjectAccessReview) GetResourceAPIVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceAPIVersion) {
		return nil, false
	}
	return o.ResourceAPIVersion, true
}

// HasResourceAPIVersion returns a boolean if a field has been set.
func (o *SubjectAccessReview) HasResourceAPIVersion() bool {
	if o != nil && !IsNil(o.ResourceAPIVersion) {
		return true
	}

	return false
}

// SetResourceAPIVersion gets a reference to the given string and assigns it to the ResourceAPIVersion field.
func (o *SubjectAccessReview) SetResourceAPIVersion(v string) {
	o.ResourceAPIVersion = &v
}

func (o SubjectAccessReview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubjectAccessReview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	toSerialize["verb"] = o.Verb
	toSerialize["resource"] = o.Resource
	if !IsNil(o.ResourceName) {
		toSerialize["resourceName"] = o.ResourceName
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.ResourceAPIGroup) {
		toSerialize["resourceAPIGroup"] = o.ResourceAPIGroup
	}
	if !IsNil(o.ResourceAPIVersion) {
		toSerialize["resourceAPIVersion"] = o.ResourceAPIVersion
	}
	return toSerialize, nil
}

type NullableSubjectAccessReview struct {
	value *SubjectAccessReview
	isSet bool
}

func (v NullableSubjectAccessReview) Get() *SubjectAccessReview {
	return v.value
}

func (v *NullableSubjectAccessReview) Set(val *SubjectAccessReview) {
	v.value = val
	v.isSet = true
}

func (v NullableSubjectAccessReview) IsSet() bool {
	return v.isSet
}

func (v *NullableSubjectAccessReview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubjectAccessReview(val *SubjectAccessReview) *NullableSubjectAccessReview {
	return &NullableSubjectAccessReview{value: val, isSet: true}
}

func (v NullableSubjectAccessReview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubjectAccessReview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


