/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GenericListClusterRole struct for GenericListClusterRole
type GenericListClusterRole struct {
	Kind *string `json:"kind,omitempty"`
	Items []ClusterRole `json:"items,omitempty"`
}

// NewGenericListClusterRole instantiates a new GenericListClusterRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenericListClusterRole() *GenericListClusterRole {
	this := GenericListClusterRole{}
	return &this
}

// NewGenericListClusterRoleWithDefaults instantiates a new GenericListClusterRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenericListClusterRoleWithDefaults() *GenericListClusterRole {
	this := GenericListClusterRole{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *GenericListClusterRole) GetKind() string {
	if o == nil || isNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericListClusterRole) GetKindOk() (*string, bool) {
	if o == nil || isNil(o.Kind) {
    return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *GenericListClusterRole) HasKind() bool {
	if o != nil && !isNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *GenericListClusterRole) SetKind(v string) {
	o.Kind = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GenericListClusterRole) GetItems() []ClusterRole {
	if o == nil || isNil(o.Items) {
		var ret []ClusterRole
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenericListClusterRole) GetItemsOk() ([]ClusterRole, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GenericListClusterRole) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ClusterRole and assigns it to the Items field.
func (o *GenericListClusterRole) SetItems(v []ClusterRole) {
	o.Items = v
}

func (o GenericListClusterRole) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableGenericListClusterRole struct {
	value *GenericListClusterRole
	isSet bool
}

func (v NullableGenericListClusterRole) Get() *GenericListClusterRole {
	return v.value
}

func (v *NullableGenericListClusterRole) Set(val *GenericListClusterRole) {
	v.value = val
	v.isSet = true
}

func (v NullableGenericListClusterRole) IsSet() bool {
	return v.isSet
}

func (v *NullableGenericListClusterRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenericListClusterRole(val *GenericListClusterRole) *NullableGenericListClusterRole {
	return &NullableGenericListClusterRole{value: val, isSet: true}
}

func (v NullableGenericListClusterRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenericListClusterRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


