/*
kafka-self-service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KafkaTopicRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KafkaTopicRequest{}

// KafkaTopicRequest struct for KafkaTopicRequest
type KafkaTopicRequest struct {
	Kind *string `json:"kind,omitempty"`
	ApiVersion *string `json:"apiVersion,omitempty"`
	Name string `json:"name"`
	Namespace *string `json:"namespace,omitempty"`
	PartitionCount *int32 `json:"partition_count,omitempty"`
	ReplicationFactor *int32 `json:"replication_factor,omitempty"`
	Configs []ConfigItem `json:"configs,omitempty"`
}

// NewKafkaTopicRequest instantiates a new KafkaTopicRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaTopicRequest(name string) *KafkaTopicRequest {
	this := KafkaTopicRequest{}
	this.Name = name
	return &this
}

// NewKafkaTopicRequestWithDefaults instantiates a new KafkaTopicRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaTopicRequestWithDefaults() *KafkaTopicRequest {
	this := KafkaTopicRequest{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *KafkaTopicRequest) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *KafkaTopicRequest) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *KafkaTopicRequest) SetKind(v string) {
	o.Kind = &v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *KafkaTopicRequest) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *KafkaTopicRequest) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *KafkaTopicRequest) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetName returns the Name field value
func (o *KafkaTopicRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KafkaTopicRequest) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *KafkaTopicRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *KafkaTopicRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *KafkaTopicRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetPartitionCount returns the PartitionCount field value if set, zero value otherwise.
func (o *KafkaTopicRequest) GetPartitionCount() int32 {
	if o == nil || IsNil(o.PartitionCount) {
		var ret int32
		return ret
	}
	return *o.PartitionCount
}

// GetPartitionCountOk returns a tuple with the PartitionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetPartitionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.PartitionCount) {
		return nil, false
	}
	return o.PartitionCount, true
}

// HasPartitionCount returns a boolean if a field has been set.
func (o *KafkaTopicRequest) HasPartitionCount() bool {
	if o != nil && !IsNil(o.PartitionCount) {
		return true
	}

	return false
}

// SetPartitionCount gets a reference to the given int32 and assigns it to the PartitionCount field.
func (o *KafkaTopicRequest) SetPartitionCount(v int32) {
	o.PartitionCount = &v
}

// GetReplicationFactor returns the ReplicationFactor field value if set, zero value otherwise.
func (o *KafkaTopicRequest) GetReplicationFactor() int32 {
	if o == nil || IsNil(o.ReplicationFactor) {
		var ret int32
		return ret
	}
	return *o.ReplicationFactor
}

// GetReplicationFactorOk returns a tuple with the ReplicationFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetReplicationFactorOk() (*int32, bool) {
	if o == nil || IsNil(o.ReplicationFactor) {
		return nil, false
	}
	return o.ReplicationFactor, true
}

// HasReplicationFactor returns a boolean if a field has been set.
func (o *KafkaTopicRequest) HasReplicationFactor() bool {
	if o != nil && !IsNil(o.ReplicationFactor) {
		return true
	}

	return false
}

// SetReplicationFactor gets a reference to the given int32 and assigns it to the ReplicationFactor field.
func (o *KafkaTopicRequest) SetReplicationFactor(v int32) {
	o.ReplicationFactor = &v
}

// GetConfigs returns the Configs field value if set, zero value otherwise.
func (o *KafkaTopicRequest) GetConfigs() []ConfigItem {
	if o == nil || IsNil(o.Configs) {
		var ret []ConfigItem
		return ret
	}
	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaTopicRequest) GetConfigsOk() ([]ConfigItem, bool) {
	if o == nil || IsNil(o.Configs) {
		return nil, false
	}
	return o.Configs, true
}

// HasConfigs returns a boolean if a field has been set.
func (o *KafkaTopicRequest) HasConfigs() bool {
	if o != nil && !IsNil(o.Configs) {
		return true
	}

	return false
}

// SetConfigs gets a reference to the given []ConfigItem and assigns it to the Configs field.
func (o *KafkaTopicRequest) SetConfigs(v []ConfigItem) {
	o.Configs = v
}

func (o KafkaTopicRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KafkaTopicRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.PartitionCount) {
		toSerialize["partition_count"] = o.PartitionCount
	}
	if !IsNil(o.ReplicationFactor) {
		toSerialize["replication_factor"] = o.ReplicationFactor
	}
	if !IsNil(o.Configs) {
		toSerialize["configs"] = o.Configs
	}
	return toSerialize, nil
}

type NullableKafkaTopicRequest struct {
	value *KafkaTopicRequest
	isSet bool
}

func (v NullableKafkaTopicRequest) Get() *KafkaTopicRequest {
	return v.value
}

func (v *NullableKafkaTopicRequest) Set(val *KafkaTopicRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaTopicRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaTopicRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaTopicRequest(val *KafkaTopicRequest) *NullableKafkaTopicRequest {
	return &NullableKafkaTopicRequest{value: val, isSet: true}
}

func (v NullableKafkaTopicRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaTopicRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


